export const LOGIN = '/api/Authservice/Login'
export const REGISTER = '/api/Authservice/Register'
export const FORGOT_PASSWORD = '/api/Authservice/SendVerifyCode'
export const RESET_PASSWORD = '/api/Authservice/ForgotPassword'
export const LIST_CUSTOMER = '/api/Customer/ListCustomer'